package com.spbau.wimag.cli.command.commands

import java.io.InputStream
import java.io.OutputStream

/**
 * Represents command that can be executed.
 * These commands generated by {#TokenCommandFactory}
 * and {#CallCommandFactory}
 */
abstract class Command {
    /**
     * Execute this command on standard input/output
     */
    fun execute() {
        execute(System.`in`, System.out)
    }

    /**
     * Execute this command on with given input/output
     * destination
     * @param input - where to read data from
     * @param output - where to write data to
     */
    abstract fun execute(input: InputStream, output: OutputStream)

}